// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(AngularCoreContext))]
    partial class AngularCoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("varchar (50)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("varchar (50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar (50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar (50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2020, 3, 12, 21, 0, 7, 784, DateTimeKind.Local).AddTicks(5926),
                            CreatedBy = 0,
                            LastModifiedBy = 0,
                            Login = "admin",
                            Name = "Administrator",
                            Password = "000"
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2020, 3, 12, 21, 0, 7, 784, DateTimeKind.Local).AddTicks(8697),
                            CreatedBy = 0,
                            LastModifiedBy = 0,
                            Login = "diego-user",
                            Name = "Diego",
                            Password = "111"
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2020, 3, 12, 21, 0, 7, 784, DateTimeKind.Local).AddTicks(8714),
                            CreatedBy = 0,
                            LastModifiedBy = 0,
                            Login = "iago-user",
                            Name = "iago",
                            Password = "222"
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2020, 3, 12, 21, 0, 7, 784, DateTimeKind.Local).AddTicks(8716),
                            CreatedBy = 0,
                            LastModifiedBy = 0,
                            Login = "fernando-user",
                            Name = "Fernando",
                            Password = "333"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
